### ISSUE TITLE
Question about Ætheral project

### ISSUE THREAD

**Issue by epsi1on** [zander/AetheralResearch#1]
Hello,
After research done, when Ætheral will be released? Do you have any plans for it?
It sounds a wonderful software! and if it have other features like normal forums (nodebb, xenforo etc.) it will be definitely good...

**Comment by zander** [comment]
You are right, its been too long..

https://www.reddit.com/r/AetheralResearch/comments/3hmxdc/update_hoping_to_actually_do_some_implementation/
